### ISSUE TITLE
CDI event Null ointer

### ISSUE THREAD

**Issue by wassimz** [peterl1084/cdiexample#5]
Hi, thanks for this great example. I am using it as a start for another project.

In one of my views, I run a runnable instance to get some object from a database. at the start of the thread, I fire up an event to disable the navigation and at the end I enable it again. Sometimes, I got the error below saying that the Event is null. Any help to fix this issue.

Thanks

at com.vaadin.cdi.internal.UIBean.<init>(UIBean.java:42) [vaadin-cdi-1.0.2.jar:1.0.2]
    at com.vaadin.cdi.internal.UIScopedContext.wrapBean(UIScopedContext.java:50) [vaadin-cdi-1.0.2.jar:1.0.2]
    at com.vaadin.cdi.internal.AbstractVaadinContext.get(AbstractVaadinContext.java:156) [vaadin-cdi-1.0.2.jar:1.0.2]
    at com.vaadin.cdi.internal.ContextWrapper.get(ContextWrapper.java:49) [vaadin-cdi-1.0.2.jar:1.0.2]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:612) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:232) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]
    at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:213) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]
    at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:117) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]
    at org.jboss.weld.event.TransactionalObserverNotifier.notifyObserver(TransactionalObserverNotifier.java:44) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]
    at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:85) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]
    at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:80) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]
    at org.jboss.weld.event.EventImpl.fire(EventImpl.java:69) [weld-core-1.1.16.Final-redhat-1.jar:1.1.16.Final-redhat-1]

**Comment by peterl1084** [comment]
When you create a new thread inside the UI layer the CDI context (current scope) is most likely not available there as it's bound only to the thread that initiated the request handling in the server which is the thread that handles the incoming HTTP request. In regular Vaadin apps it's safe to create own threads as long as they modify the UI state by using the UI.access(Runnable) method because with this approach Vaadin can internally make sure that everything is handled correctly. Still, I don't think that this enables the usage of CDI context.

Check the following:

1) Your own thread when finished (if it modifies the UI) should always do it through the UI.access(Runnable) method as this keeps the UI state consistent

2) In your own thread you cannot (most likely) inject CDI beans or otherwise reference them since the context is not active in this thread (This is my assumption, haven't tried). If the assumption is correct then using CDI managed beans would most likely result to stacktrace you're seeing above.

3) Try modifying your code to such that you don't directly modify the UI or access CDI managed beans from your own thread but instead once the processing your thread is doing is done then UI.access with different runnable for example.

4) Lastly, if the above still appears please file a bug ticket with precise description and code example to dev.vaadin.com for CDI product. In any case the above stacktrace shows that something gets broken with Vaadin-CDI when doing stuff that you're doing and it should be fixed with a reasonable error message at least.

**Comment by wassimz** [comment]
Thanks for you replies. I am already using what you are proposing. Here below the detailed scenario:
1 - In my presenter Instance, I run a runnable instance (through an ExecutorService) to select a list of object through a database
2- Inside my runnable instance, I fire an Event with a POJO containing the fetched data
3- In my View instance, I get the fired event (through an observer) and I update the UI through the UI.getCurrent.access(Runnable) and I am using a manual push (So I call UI.getCurrent().push() inside the Runnable

Notice that this stack error happen time to time and not always. Especially When I move very quickly from one view to another.

**Comment by wassimz** [comment]
Dear Peter,

Thanks again for the precious informations. The issue still appear specially sometimes when I try to fire an event from a Runnable object. I have verified that UI update is done within a separate thread through UI access method.
Currently I doesn't find a solution to fix this, but is there a way to capture application exception and display a message or a notfication for the user ??

Thanks for helping.
